### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by ChunyuPCY** [PreferredAI/beacon#1]
Hello Duc-Trong Le,
I am a reader of your beacon model. After running these codes, some problems happened. So I have some questions that I want you to answer me. Thank you!

1. in the file of "utils.py", I find some code like "basket_seq = [elements[-1]]" which confused me. Why only use last basket item information when the length of basket sequence is not 2.
2. Follow your idea, running your code, When Training the model, some item key are not in item_dict, and then error happen.

```python
def build_sparse_adjacency_matrix_v2(training_instances, validate_instances, item_dict):
    NB_ITEMS = len(item_dict)
    pairs = {}
    for line in training_instances:
        elements = line.split("|")

        if len(elements) == 3:  # basket len is 2
            basket_seq = elements[1:]  # elements[0] is label? And different label meaning?
        else:
            basket_seq = [elements[-1]]  # why only use last one, many items will not contain in item_dict

        for basket in basket_seq:
            item_list = re.split('[\\s]+', basket)
            id_list = [item_dict[item] for item in item_list]

            for t in list(itertools.product(id_list, id_list)):
                add_tuple(t, pairs)

    for line in validate_instances:
        elements = line.split("|")

        label = int(elements[0])  # label
        if label != 1 and len(elements) == 3:  # this may be related to your dataset but I can't figure out your mind.
            basket_seq = elements[1:]
        else:
            basket_seq = [elements[-1]]

        for basket in basket_seq:
            item_list = re.split('[\\s]+', basket)
            id_list = [item_dict[item] for item in item_list]

            for t in list(itertools.product(id_list, id_list)):
                add_tuple(t, pairs)

    return create_sparse_matrix(pairs, NB_ITEMS)
```
Some comments after '#' in the code above are my questions.

Thank you again for your sharing

**Comment by SSOTTY** [comment]
@ChunyuPCY do you kown why only use the last one basket?

**Comment by HerrZYZ** [comment]
I am also confused about this. And, why use the last 2 baskets only when len(elements)==3?

**Comment by trongld** [comment]
@ChunyuPCY @SSOTTY  @HerrZYZ : 
1. in the file of "utils.py", I find some code like "basket_seq = [elements[-1]]" which confused me. Why only use last basket item information when the length of basket sequence is not 2.

=> This method is to build the adjacency matrix. In order to avoid duplicate counts on computing pair frequency, hence I ignore baskets that are already considered. 

Here, a user may have multiple basket sequences because of the cut-of threshold 30. 
For examples, user A might have two sequences:
b1, b_2, ..., b_30 and b_2, b_3 ..., b_31 

2. Follow your idea, running your code, When Training the model, some item key are not in item_dict, and then error happen. 

=> I have to handle it in the pre-processing step

**Comment by SSOTTY** [comment]
@HerrZYZ add_tuple is a function and it has been added to utils.py.
